version: "3.7"

services:
  db:
    image: postgres:17
    container_name: blog_db
    env_file: 
      - .env
    ports:
      - 5432:5432
    
  redis:
    image: redis:7
    container_name: blog_redis
  
  blog:
    build:
      context: .
    container_name: blog_app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["docker/app.sh"]
    ports:
      - 7777:8000
  
  celery:
    build:
      context: .
    container_name: blog_celery
    command: ["docker/celery.sh", "celery"]
    env_file:
      - .env
    depends_on:
      - redis
  
  flower:
    build:
      context: .
    container_name: blog_flower
    command: ["docker/celery.sh", "flower"]
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis