"""Add new column - image_id for posts table

Revision ID: 14b7ea6bf7d8
Revises: 4fbc6461cc84
Create Date: 2025-03-25 19:39:51.040251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b7ea6bf7d8'
down_revision: Union[str, None] = '4fbc6461cc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_id')
    # ### end Alembic commands ###
