"""Add datetime_create for comments

Revision ID: 4fbc6461cc84
Revises: 059cba4144d6
Create Date: 2025-03-24 16:33:34.076521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbc6461cc84'
down_revision: Union[str, None] = '059cba4144d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('datetime_create', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'datetime_create')
    # ### end Alembic commands ###
